name: countriesapp
description: "Projekt zaliczeniowy - Atlas Swiata"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  hive_ce: 2.19.3
  hive_ce_flutter: 2.3.3

flutter:
  uses-material-design: true